# Generated by Django 6.1.1 on 2026-09-17 11:44

from django.db import migrations

def copia_tag_para_tags(apps, schema_editor):
    Note = apps.get_model('notes', 'Note')
    for note in Note.objects.exclude(tag=None):
        note.tags.add(note.tag)

class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_note_tags'),
    ]

    operations = [
        migrations.RunPython(copia_tag_para_tags, migrations.RunPython.noop),
    ]
