# Generated by Django 6.1.1 on 2026-09-17 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_copia_tag_para_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='tag',
        ),
    ]
