# Generated by Django 6.1.1 on 2026-09-29 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_remove_note_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.TextField()),
                ('resposta_correta', models.BooleanField()),
            ],
        ),
    ]
