# Generated by Django 6.1.1 on 2026-09-29 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='pergunta',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='perguntas', to='notes.categoria'),
            preserve_default=False,
        ),
    ]
